version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: portfolio
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql
    networks:
      - default
networks:
  default:
volumes:
  postgres_data: