version: '3.8'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=portfolio
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql-init.sql:/docker-entrypoint-initdb.d/sql-init.sql
    networks:
      - default
networks:
  default:
volumes:
  mariadb_data: